import streamlit as st
import pandas as pd
import numpy as np
import random
from datetime import datetime
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from fpdf import FPDF

# ---------------- PAGE CONFIG ----------------
st.set_page_config(page_title="SOC Phishing Detection", layout="centered")

# ---------------- MODE TOGGLE ----------------
mode = st.sidebar.radio("Select UI Mode", ["Dark Mode", "White Mode"])

# ---------------- CSS STYLING ----------------
if mode == "Dark Mode":
    st.markdown("""
    <style>
    /* Cyber animated background */
    .stApp {
        background: linear-gradient(-45deg, #020617, #020617, #020617, #020617);
        background-size: 400% 400%;
        animation: gradientBG 20s ease infinite;
    }
    @keyframes gradientBG {
        0% {background-position: 0% 50%;}
        50% {background-position: 100% 50%;}
        100% {background-position: 0% 50%;}
    }
    /* Cyber grid overlay */
    .stApp::before {
        content: "";
        position: fixed;
        top: 0; left: 0;
        width: 100%;
        height: 100%;
        background-image:
            linear-gradient(rgba(0,255,255,0.05) 1px, transparent 1px),
            linear-gradient(90deg, rgba(0,255,255,0.05) 1px, transparent 1px);
        background-size: 40px 40px;
        z-index: -1;
    }
    * { color: #ffffff !important; }
    textarea, input, .stTextArea textarea {
        background-color: #020617 !important;
        border: 1px solid #22d3ee !important;
        color: #ffffff !important;
    }
    button { background: linear-gradient(90deg, #22d3ee, #38bdf8) !important; color: #020617 !important; font-weight: 800 !important; border-radius: 12px !important; }
    .stDownloadButton button { background: linear-gradient(90deg, #38d3ee, #22bdf8) !important; color: #020617 !important; font-weight: 800 !important; }
    .css-1kyxreq, .css-1v0mbdj { background-color: rgba(2,6,23,0.85) !important; border-radius: 16px; padding: 16px; }
    </style>
    """, unsafe_allow_html=True)
else:  # White Mode
    st.markdown("""
    <style>
    .stApp { background-color: #ffffff !important; }
    * { color: #000000 !important; }
    textarea, input, .stTextArea textarea { background-color: #f2f2f2 !important; border: 1px solid #ccc !important; color: #000000 !important; }
    button { background: linear-gradient(90deg, #00aaff, #00ddff) !important; color: #000000 !important; font-weight: 800 !important; border-radius: 12px !important; }
    .stDownloadButton button { background: linear-gradient(90deg, #00ddff, #00aaff) !important; color: #000000 !important; font-weight: 800 !important; }
    .css-1kyxreq, .css-1v0mbdj { background-color: #f9f9f9 !important; border-radius: 16px; padding: 16px; }
    </style>
    """, unsafe_allow_html=True)

# ---------------- TITLE ----------------
st.title("🔐 SOC-Grade AI Phishing Detection System")
st.caption("Cyber Security UI • ML • MITRE ATT&CK • SOC Dashboard • PDF Reports")

# ---------------- TRAINING DATA ----------------
data = {
    "text": [
        "verify your account now",
        "click here to reset password",
        "urgent login required",
        "confirm your bank details",
        "win a free iphone",
        "limited offer claim now",
        "suspicious activity detected",
        "team meeting tomorrow",
        "project update attached",
        "invoice for last month",
        "weekly status report",
        "hello how are you",
        "discussion scheduled"
    ],
    "label": [1,1,1,1,1,1,1,0,0,0,0,0,0]
}

df_train = pd.DataFrame(data)
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(df_train["text"])
y = df_train["label"]
model = LogisticRegression(class_weight="balanced")
model.fit(X, y)

# ---------------- FUNCTIONS ----------------
def keyword_score(text):
    keywords = [
        "verify","urgent","click","reset","password",
        "bank","login","confirm","free","win","account"
    ]
    return sum(1 for k in keywords if k in text.lower())

def domain_age_simulation():
    age_days = random.randint(5, 3000)
    risk = max(0, 50 - int(age_days / 60))
    return age_days, risk

def generate_pdf(report):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "SOC PHISHING INCIDENT REPORT", ln=True)
    pdf.ln(6)
    pdf.set_font("Arial", "", 12)
    for k, v in report.items():
        pdf.cell(0, 8, f"{k}: {v}", ln=True)
    pdf.ln(6)
    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(
        0, 8,
        "Generated by an AI-based SOC phishing detection system "
        "for cyber-security training and awareness."
    )
    file_name = "phishing_incident_report.pdf"
    pdf.output(file_name)
    return file_name

# ---------------- INPUT ----------------
user_input = st.text_area(
    "🔍 Enter URL or Message",
    placeholder="http://secure-login.example.com/verify-account"
)

# ---------------- ANALYSIS ----------------
if st.button("Analyze Threat"):
    if user_input.strip() == "":
        st.warning("⚠ Please enter a URL or message")
    else:
        vect = vectorizer.transform([user_input])
        ml_prob = model.predict_proba(vect)[0][1] * 100
        k_score = keyword_score(user_input)
        domain_age, domain_risk = domain_age_simulation()
        risk_score = int(ml_prob * 0.6 + k_score * 8 + domain_risk)
        risk_score = min(risk_score, 100)

        if risk_score >= 65:
            verdict = "High Risk"
            st.error(f"🚨 HIGH RISK PHISHING ({risk_score}%)")
        elif risk_score >= 40:
            verdict = "Suspicious"
            st.warning(f"⚠ SUSPICIOUS CONTENT ({risk_score}%)")
        else:
            verdict = "Safe"
            st.success(f"✅ SAFE CONTENT ({risk_score}%)")

        st.subheader("🛡 SOC Indicators")
        st.write(f"• ML Confidence: {ml_prob:.1f}%")
        st.write(f"• Suspicious Keywords: {k_score}")
        st.write(f"• Domain Age (simulated): {domain_age} days")
        st.write(f"• Domain Risk Score: {domain_risk}")
        st.write(f"• Total Risk Score: {risk_score}%")

        if verdict != "Safe":
            st.subheader("🎯 MITRE ATT&CK")
            st.write("Technique: **T1566 – Phishing**")

        report = {
            "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Input": user_input,
            "RiskScore": risk_score,
            "Verdict": verdict
        }

        try:
            old = pd.read_csv("threat_reports.csv")
            df = pd.concat([old, pd.DataFrame([report])])
        except:
            df = pd.DataFrame([report])

        df.to_csv("threat_reports.csv", index=False)

        pdf_file = generate_pdf({
            "Timestamp": report["Timestamp"],
            "Input": user_input,
            "Risk": f"{risk_score}%",
            "Verdict": verdict,
            "MITRE": "T1566 - Phishing"
        })

        with open(pdf_file, "rb") as f:
            st.download_button(
                "📄 Download Incident Report (PDF)",
                f,
                file_name=pdf_file,
                mime="application/pdf"
            )

# ---------------- DASHBOARD ----------------
st.markdown("---")
st.subheader("📊 SOC Threat Intelligence Dashboard")

try:
    logs = pd.read_csv("threat_reports.csv")
    logs["Timestamp"] = pd.to_datetime(logs["Timestamp"])

    fig1, ax1 = plt.subplots()
    color_map = "skyblue" if mode=="White Mode" else "cyan"
    logs["Verdict"].value_counts().plot(kind="bar", ax=ax1, color=color_map)
    ax1.set_ylabel("Count")
    st.pyplot(fig1)

    fig2, ax2 = plt.subplots()
    logs.groupby(logs["Timestamp"].dt.date).size().plot(ax=ax2, color=color_map)
    ax2.set_ylabel("Incidents per Day")
    st.pyplot(fig2)

    st.download_button(
        "⬇ Download Threat Logs (CSV)",
        logs.to_csv(index=False),
        "threat_reports.csv",
        "text/csv"
    )

except:
    st.info("No SOC data available yet")

# ---------------- FOOTER ----------------
st.markdown("---")
st.caption("🔐 SOC-Grade AI Phishing Detection | Cyber Security UI | MITRE ATT&CK | PDF Reports")
